create table operations (id serial primary key, name text, latitude text, longitude text, zoom text, width text, height text, postfix text, current boolean, smsurl text, tetraport text, map text);
create table types (id serial primary key, name text);
create table codes (id serial primary key, code text, explanation text, ensihoito text);
create table states (id serial primary key, state text, explanation text);
create table locations (id serial primary key, location text, shortcode text, type_id integer references types(id), x integer, y integer);
create table units (id serial primary key, unit text, state_id integer references states(id), location_id integer references locations(id), listorder integer default 1, phone text, details text);
create table events (id serial primary key, code_id integer references codes(id), location_id integer references locations(id), state_id integer references states(id), unit_id integer references units(id), from_hq boolean, message text, created_at timestamp, updated_at timestamp, archived timestamp);

insert into units (unit,listorder) values ('Jono',0);
insert into units (unit,listorder) values ('Johto',2);
insert into units (unit,listorder) values ('R199',-1);
insert into units (unit,listorder) values ('Tapiola',-1);
insert into units (unit,listorder) values ('Länsi-Helsinki',-1);
insert into units (unit,listorder) values ('Itä-Helsinki',-1);
insert into units (unit,listorder) values ('Länsi-Vantaa',-1);
insert into units (unit,listorder) values ('Kontula',-1);
insert into units (unit,listorder) values ('Porvoo',-1);
insert into units (unit,listorder) values ('Vihti',-1);
insert into units (unit,listorder) values ('Snellu',-1);
insert into units (unit,listorder) values ('Mellunkylä',-1);
insert into units (unit,listorder) values ('Lasse',-1);
insert into units (unit,listorder) values ('Rauta',-1);
insert into units (unit,listorder) values ('Kaivo',-1);
insert into units (unit,listorder) values ('Senaatti',-1);
insert into units (unit,listorder) values ('Espa',-1);
insert into units (unit,listorder) values ('Vaste',-1);
insert into units (unit,listorder) values ('Partio 1',-1);
insert into units (unit,listorder) values ('Partio 2',-1);
insert into units (unit,listorder) values ('Partio 3',-1);
insert into units (unit,listorder) values ('Partio 4',-1);
insert into units (unit,listorder) values ('Partio 5',-1);
insert into units (unit,listorder) values ('Partio 6',-1);
insert into units (unit,listorder) values ('Partio 7',-1);
insert into units (unit,listorder) values ('Partio 8',-1);
insert into units (unit,listorder) values ('Partio 9',-1);
insert into units (unit,listorder) values ('Huone',-1);
insert into units (unit,listorder) values ('Huoneen vaste',-1);
insert into units (unit,listorder) values ('Nolla',-1);

insert into states (state,explanation) values ('Vapaa', 'Käytettävissä ja alueella');
insert into states (state,explanation) values ('Matkalla','Matkalla kohteeseen');
insert into states (state,explanation) values ('Kohteessa','Kohteessa, ei välttämättä potilaan luona');
insert into states (state,explanation) values ('Potilaan luona','Potilas varmasti tavoitettu');
insert into states (state,explanation) values ('Kuljettaa','Kuljettaa potilasta hoitopaikkaan');
insert into states (state,explanation) values ('Perillä','Perillä hoitopaikassa');
insert into states (state,explanation) values ('Palaa','Palaamassa alueelleen');
insert into states (state,explanation) values ('Tauolla','Tauolla');
insert into states (state,explanation) values ('Ei käytettävissä','Väliaikaisesti poissa vahvuudesta');

insert into types (id,name) values (0,'Tuntematon');
insert into types (name) values ('Hoitopaikka');
insert into types (name) values ('Asemapaikka');

insert into locations (location,shortcode,type_id) values ('Malmin sairaala','M0',1);
insert into locations (location,shortcode,type_id) values ('Haartmanin sairaala','M1',1);
insert into locations (location,shortcode,type_id) values ('Hesperian sairaala','H0',1);
insert into locations (location,shortcode,type_id) values ('Hyrylän sairaala','T2',1);
insert into locations (location,shortcode,type_id) values ('Invalidisäätiö','I1',1);
insert into locations (location,shortcode,type_id) values ('Jorvin sairaala','M5',1);
insert into locations (location,shortcode,type_id) values ('Järvenpään terveyskeskus','T3',1);
insert into locations (location,shortcode,type_id) values ('Kellokosken sairaala','H1',1);
insert into locations (location,shortcode,type_id) values ('Keravan terveyskeskus','T1',1);
insert into locations (location,shortcode,type_id) values ('Kiljava','R1',1);
insert into locations (location,shortcode,type_id) values ('Kirurginen sairaala','K1',1);
insert into locations (location,shortcode,type_id) values ('Kivelän sairaala','M3',1);
insert into locations (location,shortcode,type_id) values ('Korvaklinikka','A1',1);
insert into locations (location,shortcode,type_id) values ('Kätilöopisto','N1',1);
insert into locations (location,shortcode,type_id) values ('Lasten ja nuorten sairaala','L2',1);
insert into locations (location,shortcode,type_id) values ('Meilahden sairaala','M2',1);
insert into locations (location,shortcode,type_id) values ('Naistenklinikka','N2',1);
insert into locations (location,shortcode,type_id) values ('Nurmijärven terveyskeskus','T4',1);
insert into locations (location,shortcode,type_id) values ('Peijaksen sairaala','M6',1);
insert into locations (location,shortcode,type_id) values ('Selviämisasema','P1',1);
insert into locations (location,shortcode,type_id) values ('Riihimäen aluesairaala','M7',1);
insert into locations (location,shortcode,type_id) values ('Silmäklinikka','A2',1);
insert into locations (location,shortcode,type_id) values ('Sädehoito','S1',1);
insert into locations (location,shortcode,type_id) values ('Taivis','TN',1);
insert into locations (location,shortcode,type_id) values ('Töölön sairaala','K2',1);
insert into locations (location,shortcode,type_id) values ('Rautatientori','Rauta',2);
insert into locations (location,shortcode,type_id) values ('Senaatintori','Senaatti',2);
insert into locations (location,shortcode,type_id) values ('Kauppatori','Kauppa',2);
insert into locations (location,shortcode,type_id) values ('Esplanaadi','Espa',2);
insert into locations (location,shortcode,type_id) values ('Kaivopuisto','Kaivo',2);
insert into locations (location,shortcode,type_id) values ('Koffin puisto','Koff',2);
insert into locations (location,shortcode,type_id) values ('Hietaniemenranta','Hietsu',2);

insert into codes (code,explanation) values ('031A','Ampuminen');
insert into codes (code,explanation) values ('031B','Ampuminen');
insert into codes (code,explanation) values ('032A','Puukotus');
insert into codes (code,explanation) values ('032B','Puukotus');
insert into codes (code,explanation) values ('032C','Puukotus');
insert into codes (code,explanation) values ('033A','Potkiminen, hakkaaminen');
insert into codes (code,explanation) values ('033B','Potkiminen, hakkaaminen');
insert into codes (code,explanation) values ('033C','Potkiminen, hakkaaminen');
insert into codes (code,explanation) values ('033D','Potkiminen, hakkaaminen');
insert into codes (code,explanation) values ('034B','Pahoinpitely, tekotapa epäselvä');
insert into codes (code,explanation) values ('X-0','X: Tekninen este');
insert into codes (code,explanation) values ('X-1','X: Kuollut');
insert into codes (code,explanation) values ('X-2','X: Ohjattu poliisin suojaan');
insert into codes (code,explanation) values ('X-3','X: Pyydetty muu apu kohteeseen');
insert into codes (code,explanation) values ('X-4','X: Muu kuljetus');
insert into codes (code,explanation) values ('X-5','X: Terveyden tila määritetty, ei tarvetta ensiapuun');
insert into codes (code,explanation) values ('X-6','X: Potilas kieltäytyi');
insert into codes (code,explanation) values ('X-7','X: Potilasta ei löydetty');
insert into codes (code,explanation) values ('X-8','X: Potilas hoidettu kohteessa');
insert into codes (code,explanation) values ('X-9','X: Tehtävän peruutus');
insert into codes (code,explanation) values ('050A','Pommiuhkaus, muu');
insert into codes (code,explanation) values ('050B','Pommiuhkaus, muu');
insert into codes (code,explanation) values ('051A','Pommiuhkaus, julkinen laitos');
insert into codes (code,explanation) values ('052A','Pommiuhkaus, kulkuneuvo');
insert into codes (code,explanation) values ('052B','Pommiuhkaus, kulkuneuvo');
insert into codes (code,explanation,ensihoito) values ('700A','Eloton','eho00001');
insert into codes (code,explanation,ensihoito) values ('700B','Eloton','eho00001');
insert into codes (code,explanation,ensihoito) values ('700C','Eloton','eho00001');
insert into codes (code,explanation,ensihoito) values ('701A','Elvytys','eho00001');
insert into codes (code,explanation,ensihoito) values ('702A','Tajuttomuus','eho00008');
insert into codes (code,explanation,ensihoito) values ('702B','Tajuttomuus','eho00001');
insert into codes (code,explanation,ensihoito) values ('703A','Hengitysvaikeus','eho00009');
insert into codes (code,explanation,ensihoito) values ('703B','Hengitysvaikeus','eho00001');
insert into codes (code,explanation,ensihoito) values ('703C','Hengitysvaikeus','eho00001');
insert into codes (code,explanation,ensihoito) values ('704A','Rintakipu','eho00010');
insert into codes (code,explanation,ensihoito) values ('704B','Rintakipu','eho00001');
insert into codes (code,explanation,ensihoito) values ('704C','Rintakipu','eho00001');
insert into codes (code,explanation,ensihoito) values ('705A','Peruselintoiminnon häiriö, muu','eho00012');
insert into codes (code,explanation,ensihoito) values ('705B','Peruselintoiminnon häiriö, muu','eho00012');
insert into codes (code,explanation,ensihoito) values ('705C','Peruselintoiminnon häiriö, muu','eho00012');
insert into codes (code,explanation,ensihoito) values ('706B','Aivohalvaus','eho00013');
insert into codes (code,explanation,ensihoito) values ('706C','Aivohalvaus','eho00013');
insert into codes (code,explanation,ensihoito) values ('706D','Aivohalvaus','eho00013');
insert into codes (code,explanation) values ('710B','Tukehtuminen');
insert into codes (code,explanation) values ('711A','Ilmatie-este');
insert into codes (code,explanation) values ('711B','Ilmatie-este');
insert into codes (code,explanation) values ('711C','Ilmatie-este');
insert into codes (code,explanation) values ('712A','Jääminen suljettuun tilaan');
insert into codes (code,explanation) values ('712B','Jääminen suljettuun tilaan');
insert into codes (code,explanation) values ('712C','Jääminen suljettuun tilaan');
insert into codes (code,explanation) values ('713A','Hirttyminen, kuristuminen');
insert into codes (code,explanation) values ('713B','Hirttyminen, kuristuminen');
insert into codes (code,explanation) values ('713C','Hirttyminen, kuristuminen');
insert into codes (code,explanation) values ('714A','Hukkuminen');
insert into codes (code,explanation) values ('714B','Hukkuminen');
insert into codes (code,explanation) values ('714C','Hukkuminen');
insert into codes (code,explanation) values ('741A','Putoaminen');
insert into codes (code,explanation) values ('741B','Putoaminen');
insert into codes (code,explanation) values ('741C','Putoaminen');
insert into codes (code,explanation) values ('741D','Putoaminen');
insert into codes (code,explanation) values ('743A','Kaatuminen');
insert into codes (code,explanation) values ('743B','Kaatuminen');
insert into codes (code,explanation) values ('743C','Kaatuminen');
insert into codes (code,explanation) values ('743D','Kaatuminen');
insert into codes (code,explanation) values ('744A','Isku');
insert into codes (code,explanation) values ('744B','Isku');
insert into codes (code,explanation) values ('744C','Isku');
insert into codes (code,explanation) values ('744D','Isku');
insert into codes (code,explanation) values ('745A','Vamma, muu');
insert into codes (code,explanation) values ('745B','Vamma, muu');
insert into codes (code,explanation) values ('745C','Vamma, muu');
insert into codes (code,explanation) values ('745D','Vamma, muu');
insert into codes (code,explanation) values ('742A','Haava');
insert into codes (code,explanation) values ('742B','Haava');
insert into codes (code,explanation) values ('742C','Haava');
insert into codes (code,explanation) values ('742D','Haava');
insert into codes (code,explanation) values ('751A','Kaasumyrkytys');
insert into codes (code,explanation) values ('751B','Kaasumyrkytys');
insert into codes (code,explanation) values ('751C','Kaasumyrkytys');
insert into codes (code,explanation) values ('752A','Myrkytys');
insert into codes (code,explanation) values ('752B','Myrkytys');
insert into codes (code,explanation) values ('752C','Myrkytys');
insert into codes (code,explanation) values ('752D','Myrkytys');
insert into codes (code,explanation) values ('753A','Sähköisku');
insert into codes (code,explanation) values ('753B','Sähköisku');
insert into codes (code,explanation) values ('753C','Sähköisku');
insert into codes (code,explanation) values ('754A','Palovamma');
insert into codes (code,explanation) values ('754B','Palovamma');
insert into codes (code,explanation) values ('754C','Palovamma');
insert into codes (code,explanation) values ('754D','Palovamma');
insert into codes (code,explanation) values ('755A','Ylilämpöisyys');
insert into codes (code,explanation) values ('755B','Ylilämpöisyys');
insert into codes (code,explanation) values ('755C','Ylilämpöisyys');
insert into codes (code,explanation) values ('756A','Paleltuminen, alilämpöisyys');
insert into codes (code,explanation) values ('756B','Paleltuminen, alilämpöisyys');
insert into codes (code,explanation) values ('756C','Paleltuminen, alilämpöisyys');
insert into codes (code,explanation) values ('757A','Onnettomuus, muu');
insert into codes (code,explanation) values ('757B','Onnettomuus, muu');
insert into codes (code,explanation) values ('757C','Onnettomuus, muu');
insert into codes (code,explanation) values ('761A','Verenvuoto suusta');
insert into codes (code,explanation) values ('761B','Verenvuoto suusta');
insert into codes (code,explanation) values ('761C','Verenvuoto suusta');
insert into codes (code,explanation) values ('762B','Verenvuoto gynekologinen/urologinen');
insert into codes (code,explanation) values ('762C','Verenvuoto gynekologinen/urologinen');
insert into codes (code,explanation) values ('762D','Verenvuoto gynekologinen/urologinen');
insert into codes (code,explanation) values ('763B','Verenvuoto korva/nenä');
insert into codes (code,explanation) values ('763C','Verenvuoto korva/nenä');
insert into codes (code,explanation) values ('763D','Verenvuoto korva/nenä');
insert into codes (code,explanation) values ('764B','Verenvuoto sääri/muu');
insert into codes (code,explanation) values ('764C','Verenvuoto sääri/muu');
insert into codes (code,explanation) values ('764D','Verenvuoto sääri/muu');
insert into codes (code,explanation) values ('770B','Sairauskohtaus');
insert into codes (code,explanation) values ('771A','Sokeritasapainon häiriö');
insert into codes (code,explanation) values ('771B','Sokeritasapainon häiriö');
insert into codes (code,explanation) values ('771C','Sokeritasapainon häiriö');
insert into codes (code,explanation) values ('772A','Kouristelu');
insert into codes (code,explanation) values ('772B','Kouristelu');
insert into codes (code,explanation) values ('772C','Kouristelu');
insert into codes (code,explanation) values ('772D','Kouristelu');
insert into codes (code,explanation) values ('773A','Yliherkkyysreaktio');
insert into codes (code,explanation) values ('773B','Yliherkkyysreaktio');
insert into codes (code,explanation) values ('773C','Yliherkkyysreaktio');
insert into codes (code,explanation) values ('773D','Yliherkkyysreaktio');
insert into codes (code,explanation) values ('774C','Heikentynyt yleistila');
insert into codes (code,explanation) values ('774D','Heikentynyt yleistila');
insert into codes (code,explanation) values ('775C','Oksentelu, ripuli');
insert into codes (code,explanation) values ('775D','Oksentelu, ripuli');
insert into codes (code,explanation) values ('781A','Vatsakipu');
insert into codes (code,explanation) values ('781B','Vatsakipu');
insert into codes (code,explanation) values ('781C','Vatsakipu');
insert into codes (code,explanation) values ('781D','Vatsakipu');
insert into codes (code,explanation) values ('782A','Pää/niskasärky');
insert into codes (code,explanation) values ('782B','Pää/niskasärky');
insert into codes (code,explanation) values ('782C','Pää/niskasärky');
insert into codes (code,explanation) values ('782D','Pää/niskasärky');
insert into codes (code,explanation) values ('783B','Selkä/raaja/vartalokipu');
insert into codes (code,explanation) values ('783C','Selkä/raaja/vartalokipu');
insert into codes (code,explanation) values ('783D','Selkä/raaja/vartalokipu');
insert into codes (code,explanation) values ('784C','Aistioire');
insert into codes (code,explanation) values ('784D','Aistioire');
insert into codes (code,explanation) values ('785C','Mielenterveysongelma');
insert into codes (code,explanation) values ('785D','Mielenterveysongelma');
insert into codes (code,explanation) values ('790B','Epäselvä tehtävä');
insert into codes (code,explanation) values ('791A','Synnytys');
insert into codes (code,explanation) values ('791B','Synnytys');
insert into codes (code,explanation) values ('791C','Synnytys');
insert into codes (code,explanation) values ('791D','Synnytys');
insert into codes (code,explanation) values ('792B','Uhkailu, varuillaolo');
insert into codes (code,explanation) values ('792C','Uhkailu, varuillaolo');
insert into codes (code,explanation) values ('793A','Hoitolaitossiirto');
insert into codes (code,explanation) values ('793B','Hoitolaitossiirto');
insert into codes (code,explanation) values ('793C','Hoitolaitossiirto');
insert into codes (code,explanation) values ('793D','Hoitolaitossiirto');
insert into codes (code,explanation) values ('794D','Muu sairaankuljetustehtävä');
insert into codes (code,explanation) values ('796A','Monipotilastilanne, suuronnettomuus');
insert into codes (code,explanation) values ('202A','Tieliikennonnettomuus, pieni');
insert into codes (code,explanation) values ('202B','Tieliikennonnettomuus, pieni');
insert into codes (code,explanation) values ('202C','Tieliikennonnettomuus, pieni');
insert into codes (code,explanation) values ('203A','Tieliikennonnettomuus, keskisuuri');
insert into codes (code,explanation) values ('203B','Tieliikennonnettomuus, keskisuuri');
insert into codes (code,explanation) values ('203C','Tieliikennonnettomuus, keskisuuri');
insert into codes (code,explanation) values ('204A','Tieliikennonnettomuus, suuri');
insert into codes (code,explanation) values ('204B','Tieliikennonnettomuus, suuri');
insert into codes (code,explanation) values ('212A','Raideliikennonnettomuus, pieni');
insert into codes (code,explanation) values ('212B','Raideliikennonnettomuus, pieni');
insert into codes (code,explanation) values ('213A','Raideliikennonnettomuus, keskisuuri');
insert into codes (code,explanation) values ('213B','Raideliikennonnettomuus, keskisuuri');
insert into codes (code,explanation) values ('214A','Raideliikennonnettomuus, suuri');
insert into codes (code,explanation) values ('214B','Raideliikennonnettomuus, suuri');
insert into codes (code,explanation) values ('220A','Vesiliikennonnettomuus, muu');
insert into codes (code,explanation) values ('220B','Vesiliikennonnettomuus, muu');
insert into codes (code,explanation) values ('221A','Vesiliikennonnettomuus, pieni');
insert into codes (code,explanation) values ('221B','Vesiliikennonnettomuus, pieni');
insert into codes (code,explanation) values ('222A','Vesiliikennonnettomuus, keskisuuri');
insert into codes (code,explanation) values ('222B','Vesiliikennonnettomuus, keskisuuri');
insert into codes (code,explanation) values ('223A','Vesiliikennonnettomuus, suuri');
insert into codes (code,explanation) values ('223B','Vesiliikennonnettomuus, suuri');
