create table operations (id integer primary key, name text, latitude text, longitude text, zoom text, width text, height text, postfix text, current boolean, smsurl text, tetraport text, map text);
create table types (id integer primary key, name text);
create table codes (id integer primary key, code text, explanation text, ensihoito text);
create table states (id integer primary key, state text, explanation text);
create table locations (id integer primary key, location text, shortcode text, type_id integer references types(id), x integer, y integer);
create table units (id integer primary key, unit text, state_id integer references states(id), location_id integer references locations(id), listorder integer default 1, phone text, imei text, details text, created_at timestamp, updated_at timestamp);
create table events (id integer primary key, code_id integer references codes(id), location_id integer references locations(id), state_id integer references states(id), unit_id integer references units(id), from_hq boolean, message text, created_at timestamp, updated_at timestamp, archived timestamp);

insert into units (id,unit,listorder) values (-1,'Jono',0);
insert into units (id,unit,listorder) values (-2,'Johto',2);
insert into units (id,unit,listorder) values (-3,'Vaste',-1);
insert into units (id,unit,listorder) values (-4,'Partio 1',-1);
insert into units (id,unit,listorder) values (-5,'Partio 2',-1);
insert into units (id,unit,listorder) values (-6,'Partio 3',-1);
insert into units (id,unit,listorder) values (-7,'Partio 4',-1);
insert into units (id,unit,listorder) values (-8,'Partio 5',-1);
insert into units (id,unit,listorder) values (-9,'Partio 6',-1);
insert into units (id,unit,listorder) values (-10,'Partio 7',-1);
insert into units (id,unit,listorder) values (-11,'Partio 8',-1);
insert into units (id,unit,listorder) values (-12,'Partio 9',-1);

insert into states (id,state,explanation) values (1,'Vapaa', 'Käytettävissä ja alueella');
insert into states (id,state,explanation) values (2,'Matkalla','Matkalla kohteeseen');
insert into states (id,state,explanation) values (3,'Kohteessa','Kohteessa, ei välttämättä potilaan luona');
insert into states (id,state,explanation) values (4,'Potilaan luona','Potilas varmasti tavoitettu');
insert into states (id,state,explanation) values (5,'Kuljettaa','Kuljettaa potilasta hoitopaikkaan');
insert into states (id,state,explanation) values (6,'Perillä','Perillä hoitopaikassa');
insert into states (id,state,explanation) values (7,'Palaa','Palaamassa alueelleen');
insert into states (id,state,explanation) values (8,'Tauolla','Tauolla');
insert into states (id,state,explanation) values (9,'Ei käytettävissä','Väliaikaisesti poissa vahvuudesta');

insert into types (id,name) values (0,'Tuntematon');
insert into types (id,name) values (1,'Hoitopaikka');
insert into types (id,name) values (2,'Asemapaikka');

insert into codes (id,code,explanation) values (-1,'031A','Ampuminen');
insert into codes (id,code,explanation) values (-2,'031B','Ampuminen');
insert into codes (id,code,explanation) values (-3,'032A','Puukotus');
insert into codes (id,code,explanation) values (-4,'032B','Puukotus');
insert into codes (id,code,explanation) values (-5,'032C','Puukotus');
insert into codes (id,code,explanation) values (-6,'033A','Potkiminen, hakkaaminen');
insert into codes (id,code,explanation) values (-7,'033B','Potkiminen, hakkaaminen');
insert into codes (id,code,explanation) values (-8,'033C','Potkiminen, hakkaaminen');
insert into codes (id,code,explanation) values (-9,'033D','Potkiminen, hakkaaminen');
insert into codes (id,code,explanation) values (-10,'034B','Pahoinpitely, tekotapa epäselvä');
insert into codes (id,code,explanation) values (-11,'X-0','X: Tekninen este');
insert into codes (id,code,explanation) values (-12,'X-1','X: Kuollut');
insert into codes (id,code,explanation) values (-13,'X-2','X: Ohjattu poliisin suojaan');
insert into codes (id,code,explanation) values (-14,'X-3','X: Pyydetty muu apu kohteeseen');
insert into codes (id,code,explanation) values (-15,'X-4','X: Muu kuljetus');
insert into codes (id,code,explanation) values (-16,'X-5','X: Terveyden tila määritetty, ei tarvetta ensiapuun');
insert into codes (id,code,explanation) values (-17,'X-6','X: Potilas kieltäytyi');
insert into codes (id,code,explanation) values (-18,'X-7','X: Potilasta ei löydetty');
insert into codes (id,code,explanation) values (-19,'X-8','X: Potilas hoidettu kohteessa');
insert into codes (id,code,explanation) values (-20,'X-9','X: Tehtävän peruutus');
insert into codes (id,code,explanation) values (-21,'050A','Pommiuhkaus, muu');
insert into codes (id,code,explanation) values (-22,'050B','Pommiuhkaus, muu');
insert into codes (id,code,explanation) values (-23,'051A','Pommiuhkaus, julkinen laitos');
insert into codes (id,code,explanation) values (-24,'052A','Pommiuhkaus, kulkuneuvo');
insert into codes (id,code,explanation) values (-25,'052B','Pommiuhkaus, kulkuneuvo');
insert into codes (id,code,explanation,ensihoito) values (-26,'700A','Eloton','eho00001');
insert into codes (id,code,explanation,ensihoito) values (-27,'700B','Eloton','eho00001');
insert into codes (id,code,explanation,ensihoito) values (-28,'700C','Eloton','eho00001');
insert into codes (id,code,explanation,ensihoito) values (-29,'701A','Elvytys','eho00001');
insert into codes (id,code,explanation,ensihoito) values (-30,'702A','Tajuttomuus','eho00008');
insert into codes (id,code,explanation,ensihoito) values (-31,'702B','Tajuttomuus','eho00001');
insert into codes (id,code,explanation,ensihoito) values (-32,'703A','Hengitysvaikeus','eho00009');
insert into codes (id,code,explanation,ensihoito) values (-33,'703B','Hengitysvaikeus','eho00001');
insert into codes (id,code,explanation,ensihoito) values (-34,'703C','Hengitysvaikeus','eho00001');
insert into codes (id,code,explanation,ensihoito) values (-35,'704A','Rintakipu','eho00010');
insert into codes (id,code,explanation,ensihoito) values (-36,'704B','Rintakipu','eho00001');
insert into codes (id,code,explanation,ensihoito) values (-37,'704C','Rintakipu','eho00001');
insert into codes (id,code,explanation,ensihoito) values (-38,'705A','Peruselintoiminnon häiriö, muu','eho00012');
insert into codes (id,code,explanation,ensihoito) values (-39,'705B','Peruselintoiminnon häiriö, muu','eho00012');
insert into codes (id,code,explanation,ensihoito) values (-40,'705C','Peruselintoiminnon häiriö, muu','eho00012');
insert into codes (id,code,explanation,ensihoito) values (-41,'706B','Aivohalvaus','eho00013');
insert into codes (id,code,explanation,ensihoito) values (-42,'706C','Aivohalvaus','eho00013');
insert into codes (id,code,explanation,ensihoito) values (-43,'706D','Aivohalvaus','eho00013');
insert into codes (id,code,explanation) values (-44,'710B','Tukehtuminen');
insert into codes (id,code,explanation) values (-45,'711A','Ilmatie-este');
insert into codes (id,code,explanation) values (-46,'711B','Ilmatie-este');
insert into codes (id,code,explanation) values (-47,'711C','Ilmatie-este');
insert into codes (id,code,explanation) values (-48,'712A','Jääminen suljettuun tilaan');
insert into codes (id,code,explanation) values (-49,'712B','Jääminen suljettuun tilaan');
insert into codes (id,code,explanation) values (-50,'712C','Jääminen suljettuun tilaan');
insert into codes (id,code,explanation) values (-51,'713A','Hirttyminen, kuristuminen');
insert into codes (id,code,explanation) values (-52,'713B','Hirttyminen, kuristuminen');
insert into codes (id,code,explanation) values (-53,'713C','Hirttyminen, kuristuminen');
insert into codes (id,code,explanation) values (-54,'714A','Hukkuminen');
insert into codes (id,code,explanation) values (-55,'714B','Hukkuminen');
insert into codes (id,code,explanation) values (-56,'714C','Hukkuminen');
insert into codes (id,code,explanation) values (-57,'741A','Putoaminen');
insert into codes (id,code,explanation) values (-58,'741B','Putoaminen');
insert into codes (id,code,explanation) values (-59,'741C','Putoaminen');
insert into codes (id,code,explanation) values (-60,'741D','Putoaminen');
insert into codes (id,code,explanation) values (-61,'743A','Kaatuminen');
insert into codes (id,code,explanation) values (-62,'743B','Kaatuminen');
insert into codes (id,code,explanation) values (-63,'743C','Kaatuminen');
insert into codes (id,code,explanation) values (-64,'743D','Kaatuminen');
insert into codes (id,code,explanation) values (-65,'744A','Isku');
insert into codes (id,code,explanation) values (-66,'744B','Isku');
insert into codes (id,code,explanation) values (-67,'744C','Isku');
insert into codes (id,code,explanation) values (-68,'744D','Isku');
insert into codes (id,code,explanation) values (-69,'745A','Vamma, muu');
insert into codes (id,code,explanation) values (-70,'745B','Vamma, muu');
insert into codes (id,code,explanation) values (-71,'745C','Vamma, muu');
insert into codes (id,code,explanation) values (-72,'745D','Vamma, muu');
insert into codes (id,code,explanation) values (-73,'742A','Haava');
insert into codes (id,code,explanation) values (-74,'742B','Haava');
insert into codes (id,code,explanation) values (-75,'742C','Haava');
insert into codes (id,code,explanation) values (-76,'742D','Haava');
insert into codes (id,code,explanation) values (-77,'751A','Kaasumyrkytys');
insert into codes (id,code,explanation) values (-78,'751B','Kaasumyrkytys');
insert into codes (id,code,explanation) values (-79,'751C','Kaasumyrkytys');
insert into codes (id,code,explanation) values (-80,'752A','Myrkytys');
insert into codes (id,code,explanation) values (-81,'752B','Myrkytys');
insert into codes (id,code,explanation) values (-82,'752C','Myrkytys');
insert into codes (id,code,explanation) values (-83,'752D','Myrkytys');
insert into codes (id,code,explanation) values (-84,'753A','Sähköisku');
insert into codes (id,code,explanation) values (-85,'753B','Sähköisku');
insert into codes (id,code,explanation) values (-86,'753C','Sähköisku');
insert into codes (id,code,explanation) values (-87,'754A','Palovamma');
insert into codes (id,code,explanation) values (-88,'754B','Palovamma');
insert into codes (id,code,explanation) values (-89,'754C','Palovamma');
insert into codes (id,code,explanation) values (-90,'754D','Palovamma');
insert into codes (id,code,explanation) values (-91,'755A','Ylilämpöisyys');
insert into codes (id,code,explanation) values (-92,'755B','Ylilämpöisyys');
insert into codes (id,code,explanation) values (-93,'755C','Ylilämpöisyys');
insert into codes (id,code,explanation) values (-94,'756A','Paleltuminen, alilämpöisyys');
insert into codes (id,code,explanation) values (-95,'756B','Paleltuminen, alilämpöisyys');
insert into codes (id,code,explanation) values (-96,'756C','Paleltuminen, alilämpöisyys');
insert into codes (id,code,explanation) values (-97,'757A','Onnettomuus, muu');
insert into codes (id,code,explanation) values (-98,'757B','Onnettomuus, muu');
insert into codes (id,code,explanation) values (-99,'757C','Onnettomuus, muu');
insert into codes (id,code,explanation) values (-100,'761A','Verenvuoto suusta');
insert into codes (id,code,explanation) values (-101,'761B','Verenvuoto suusta');
insert into codes (id,code,explanation) values (-102,'761C','Verenvuoto suusta');
insert into codes (id,code,explanation) values (-103,'762B','Verenvuoto gynekologinen/urologinen');
insert into codes (id,code,explanation) values (-104,'762C','Verenvuoto gynekologinen/urologinen');
insert into codes (id,code,explanation) values (-105,'762D','Verenvuoto gynekologinen/urologinen');
insert into codes (id,code,explanation) values (-106,'763B','Verenvuoto korva/nenä');
insert into codes (id,code,explanation) values (-107,'763C','Verenvuoto korva/nenä');
insert into codes (id,code,explanation) values (-108,'763D','Verenvuoto korva/nenä');
insert into codes (id,code,explanation) values (-109,'764B','Verenvuoto sääri/muu');
insert into codes (id,code,explanation) values (-110,'764C','Verenvuoto sääri/muu');
insert into codes (id,code,explanation) values (-111,'764D','Verenvuoto sääri/muu');
insert into codes (id,code,explanation) values (-112,'770B','Sairauskohtaus');
insert into codes (id,code,explanation) values (-113,'771A','Sokeritasapainon häiriö');
insert into codes (id,code,explanation) values (-114,'771B','Sokeritasapainon häiriö');
insert into codes (id,code,explanation) values (-115,'771C','Sokeritasapainon häiriö');
insert into codes (id,code,explanation) values (-116,'772A','Kouristelu');
insert into codes (id,code,explanation) values (-117,'772B','Kouristelu');
insert into codes (id,code,explanation) values (-118,'772C','Kouristelu');
insert into codes (id,code,explanation) values (-119,'772D','Kouristelu');
insert into codes (id,code,explanation) values (-120,'773A','Yliherkkyysreaktio');
insert into codes (id,code,explanation) values (-121,'773B','Yliherkkyysreaktio');
insert into codes (id,code,explanation) values (-122,'773C','Yliherkkyysreaktio');
insert into codes (id,code,explanation) values (-123,'773D','Yliherkkyysreaktio');
insert into codes (id,code,explanation) values (-124,'774C','Heikentynyt yleistila');
insert into codes (id,code,explanation) values (-125,'774D','Heikentynyt yleistila');
insert into codes (id,code,explanation) values (-126,'775C','Oksentelu, ripuli');
insert into codes (id,code,explanation) values (-127,'775D','Oksentelu, ripuli');
insert into codes (id,code,explanation) values (-128,'781A','Vatsakipu');
insert into codes (id,code,explanation) values (-129,'781B','Vatsakipu');
insert into codes (id,code,explanation) values (-130,'781C','Vatsakipu');
insert into codes (id,code,explanation) values (-131,'781D','Vatsakipu');
insert into codes (id,code,explanation) values (-132,'782A','Pää/niskasärky');
insert into codes (id,code,explanation) values (-133,'782B','Pää/niskasärky');
insert into codes (id,code,explanation) values (-134,'782C','Pää/niskasärky');
insert into codes (id,code,explanation) values (-135,'782D','Pää/niskasärky');
insert into codes (id,code,explanation) values (-136,'783B','Selkä/raaja/vartalokipu');
insert into codes (id,code,explanation) values (-137,'783C','Selkä/raaja/vartalokipu');
insert into codes (id,code,explanation) values (-138,'783D','Selkä/raaja/vartalokipu');
insert into codes (id,code,explanation) values (-139,'784C','Aistioire');
insert into codes (id,code,explanation) values (-140,'784D','Aistioire');
insert into codes (id,code,explanation) values (-141,'785C','Mielenterveysongelma');
insert into codes (id,code,explanation) values (-142,'785D','Mielenterveysongelma');
insert into codes (id,code,explanation) values (-143,'790B','Epäselvä tehtävä');
insert into codes (id,code,explanation) values (-144,'791A','Synnytys');
insert into codes (id,code,explanation) values (-145,'791B','Synnytys');
insert into codes (id,code,explanation) values (-146,'791C','Synnytys');
insert into codes (id,code,explanation) values (-147,'791D','Synnytys');
insert into codes (id,code,explanation) values (-148,'792B','Uhkailu, varuillaolo');
insert into codes (id,code,explanation) values (-149,'792C','Uhkailu, varuillaolo');
insert into codes (id,code,explanation) values (-150,'793A','Hoitolaitossiirto');
insert into codes (id,code,explanation) values (-151,'793B','Hoitolaitossiirto');
insert into codes (id,code,explanation) values (-152,'793C','Hoitolaitossiirto');
insert into codes (id,code,explanation) values (-153,'793D','Hoitolaitossiirto');
insert into codes (id,code,explanation) values (-154,'794D','Muu sairaankuljetustehtävä');
insert into codes (id,code,explanation) values (-155,'796A','Monipotilastilanne, suuronnettomuus');
insert into codes (id,code,explanation) values (-156,'202A','Tieliikennonnettomuus, pieni');
insert into codes (id,code,explanation) values (-157,'202B','Tieliikennonnettomuus, pieni');
insert into codes (id,code,explanation) values (-158,'202C','Tieliikennonnettomuus, pieni');
insert into codes (id,code,explanation) values (-159,'203A','Tieliikennonnettomuus, keskisuuri');
insert into codes (id,code,explanation) values (-160,'203B','Tieliikennonnettomuus, keskisuuri');
insert into codes (id,code,explanation) values (-161,'203C','Tieliikennonnettomuus, keskisuuri');
insert into codes (id,code,explanation) values (-162,'204A','Tieliikennonnettomuus, suuri');
insert into codes (id,code,explanation) values (-163,'204B','Tieliikennonnettomuus, suuri');
insert into codes (id,code,explanation) values (-164,'212A','Raideliikennonnettomuus, pieni');
insert into codes (id,code,explanation) values (-165,'212B','Raideliikennonnettomuus, pieni');
insert into codes (id,code,explanation) values (-167,'213A','Raideliikennonnettomuus, keskisuuri');
insert into codes (id,code,explanation) values (-168,'213B','Raideliikennonnettomuus, keskisuuri');
insert into codes (id,code,explanation) values (-169,'214A','Raideliikennonnettomuus, suuri');
insert into codes (id,code,explanation) values (-170,'214B','Raideliikennonnettomuus, suuri');
insert into codes (id,code,explanation) values (-171,'220A','Vesiliikennonnettomuus, muu');
insert into codes (id,code,explanation) values (-172,'220B','Vesiliikennonnettomuus, muu');
insert into codes (id,code,explanation) values (-173,'221A','Vesiliikennonnettomuus, pieni');
insert into codes (id,code,explanation) values (-174,'221B','Vesiliikennonnettomuus, pieni');
insert into codes (id,code,explanation) values (-175,'222A','Vesiliikennonnettomuus, keskisuuri');
insert into codes (id,code,explanation) values (-176,'222B','Vesiliikennonnettomuus, keskisuuri');
insert into codes (id,code,explanation) values (-177,'223A','Vesiliikennonnettomuus, suuri');
insert into codes (id,code,explanation) values (-178,'223B','Vesiliikennonnettomuus, suuri');
