class CreateCodes < ActiveRecord::Migration
  def self.up
    create_table :codes do |t|
      t.string :code
      t.string :explanation
      t.timestamps
    end

    Code.create :code => "031A", :explanation => "Ampuminen"
    Code.create :code => "031B", :explanation => "Ampuminen"
    Code.create :code => "032A", :explanation => "Puukotus"
    Code.create :code => "032B", :explanation => "Puukotus"
    Code.create :code => "032C", :explanation => "Puukotus"
    Code.create :code => "033A", :explanation => "Potkiminen, hakkaaminen"
    Code.create :code => "033B", :explanation => "Potkiminen, hakkaaminen"
    Code.create :code => "033C", :explanation => "Potkiminen, hakkaaminen"
    Code.create :code => "033D", :explanation => "Potkiminen, hakkaaminen"
    Code.create :code => "034B", :explanation => "Pahoinpitely, tekotapa epäselvä"
    Code.create :code => "X-0", :explanation => "X: Tekninen este"
    Code.create :code => "X-1", :explanation => "X: Kuollut"
    Code.create :code => "X-2", :explanation => "X: Ohjattu poliisin suojaan"
    Code.create :code => "X-3", :explanation => "X: Pyydetty muu apu kohteeseen"
    Code.create :code => "X-4", :explanation => "X: Muu kuljetus"
    Code.create :code => "X-5", :explanation => "X: Terveyden tila määritetty, ei tarvetta ensiapuun"
    Code.create :code => "X-6", :explanation => "X: Potilas kieltäytyi"
    Code.create :code => "X-7", :explanation => "X: Potilasta ei löydetty"
    Code.create :code => "X-8", :explanation => "X: Potilas hoidettu kohteessa"
    Code.create :code => "X-9", :explanation => "X: Tehtävän peruutus"
    Code.create :code => "050A", :explanation => "Pommiuhkaus, muu"
    Code.create :code => "050B", :explanation => "Pommiuhkaus, muu"
    Code.create :code => "051A", :explanation => "Pommiuhkaus, julkinen laitos"
    Code.create :code => "052A", :explanation => "Pommiuhkaus, kulkuneuvo"
    Code.create :code => "052B", :explanation => "Pommiuhkaus, kulkuneuvo"
    insert into codes (code,explanation,ensihoito) values :code => "700A", :explanation => "Eloton", :explanation => "eho00001"
    insert into codes (code,explanation,ensihoito) values :code => "700B", :explanation => "Eloton", :explanation => "eho00001"
    insert into codes (code,explanation,ensihoito) values :code => "700C", :explanation => "Eloton", :explanation => "eho00001"
    insert into codes (code,explanation,ensihoito) values :code => "701A", :explanation => "Elvytys", :explanation => "eho00001"
    insert into codes (code,explanation,ensihoito) values :code => "702A", :explanation => "Tajuttomuus", :explanation => "eho00008"
    insert into codes (code,explanation,ensihoito) values :code => "702B", :explanation => "Tajuttomuus", :explanation => "eho00001"
    insert into codes (code,explanation,ensihoito) values :code => "703A", :explanation => "Hengitysvaikeus", :explanation => "eho00009"
    insert into codes (code,explanation,ensihoito) values :code => "703B", :explanation => "Hengitysvaikeus", :explanation => "eho00001"
    insert into codes (code,explanation,ensihoito) values :code => "703C", :explanation => "Hengitysvaikeus", :explanation => "eho00001"
    insert into codes (code,explanation,ensihoito) values :code => "704A", :explanation => "Rintakipu", :explanation => "eho00010"
    insert into codes (code,explanation,ensihoito) values :code => "704B", :explanation => "Rintakipu", :explanation => "eho00001"
    insert into codes (code,explanation,ensihoito) values :code => "704C", :explanation => "Rintakipu", :explanation => "eho00001"
    insert into codes (code,explanation,ensihoito) values :code => "705A", :explanation => "Peruselintoiminnon häiriö, muu", :explanation => "eho00012"
    insert into codes (code,explanation,ensihoito) values :code => "705B", :explanation => "Peruselintoiminnon häiriö, muu", :explanation => "eho00012"
    insert into codes (code,explanation,ensihoito) values :code => "705C", :explanation => "Peruselintoiminnon häiriö, muu", :explanation => "eho00012"
    insert into codes (code,explanation,ensihoito) values :code => "706B", :explanation => "Aivohalvaus", :explanation => "eho00013"
    insert into codes (code,explanation,ensihoito) values :code => "706C", :explanation => "Aivohalvaus", :explanation => "eho00013"
    insert into codes (code,explanation,ensihoito) values :code => "706D", :explanation => "Aivohalvaus", :explanation => "eho00013"
    Code.create :code => "710B", :explanation => "Tukehtuminen"
    Code.create :code => "711A", :explanation => "Ilmatie-este"
    Code.create :code => "711B", :explanation => "Ilmatie-este"
    Code.create :code => "711C", :explanation => "Ilmatie-este"
    Code.create :code => "712A", :explanation => "Jääminen suljettuun tilaan"
    Code.create :code => "712B", :explanation => "Jääminen suljettuun tilaan"
    Code.create :code => "712C", :explanation => "Jääminen suljettuun tilaan"
    Code.create :code => "713A", :explanation => "Hirttyminen, kuristuminen"
    Code.create :code => "713B", :explanation => "Hirttyminen, kuristuminen"
    Code.create :code => "713C", :explanation => "Hirttyminen, kuristuminen"
    Code.create :code => "714A", :explanation => "Hukkuminen"
    Code.create :code => "714B", :explanation => "Hukkuminen"
    Code.create :code => "714C", :explanation => "Hukkuminen"
    Code.create :code => "741A", :explanation => "Putoaminen"
    Code.create :code => "741B", :explanation => "Putoaminen"
    Code.create :code => "741C", :explanation => "Putoaminen"
    Code.create :code => "741D", :explanation => "Putoaminen"
    Code.create :code => "743A", :explanation => "Kaatuminen"
    Code.create :code => "743B", :explanation => "Kaatuminen"
    Code.create :code => "743C", :explanation => "Kaatuminen"
    Code.create :code => "743D", :explanation => "Kaatuminen"
    Code.create :code => "744A", :explanation => "Isku"
    Code.create :code => "744B", :explanation => "Isku"
    Code.create :code => "744C", :explanation => "Isku"
    Code.create :code => "744D", :explanation => "Isku"
    Code.create :code => "745A", :explanation => "Vamma, muu"
    Code.create :code => "745B", :explanation => "Vamma, muu"
    Code.create :code => "745C", :explanation => "Vamma, muu"
    Code.create :code => "745D", :explanation => "Vamma, muu"
    Code.create :code => "742A", :explanation => "Haava"
    Code.create :code => "742B", :explanation => "Haava"
    Code.create :code => "742C", :explanation => "Haava"
    Code.create :code => "742D", :explanation => "Haava"
    Code.create :code => "751A", :explanation => "Kaasumyrkytys"
    Code.create :code => "751B", :explanation => "Kaasumyrkytys"
    Code.create :code => "751C", :explanation => "Kaasumyrkytys"
    Code.create :code => "752A", :explanation => "Myrkytys"
    Code.create :code => "752B", :explanation => "Myrkytys"
    Code.create :code => "752C", :explanation => "Myrkytys"
    Code.create :code => "752D", :explanation => "Myrkytys"
    Code.create :code => "753A", :explanation => "Sähköisku"
    Code.create :code => "753B", :explanation => "Sähköisku"
    Code.create :code => "753C", :explanation => "Sähköisku"
    Code.create :code => "754A", :explanation => "Palovamma"
    Code.create :code => "754B", :explanation => "Palovamma"
    Code.create :code => "754C", :explanation => "Palovamma"
    Code.create :code => "754D", :explanation => "Palovamma"
    Code.create :code => "755A", :explanation => "Ylilämpöisyys"
    Code.create :code => "755B", :explanation => "Ylilämpöisyys"
    Code.create :code => "755C", :explanation => "Ylilämpöisyys"
    Code.create :code => "756A", :explanation => "Paleltuminen, alilämpöisyys"
    Code.create :code => "756B", :explanation => "Paleltuminen, alilämpöisyys"
    Code.create :code => "756C", :explanation => "Paleltuminen, alilämpöisyys"
    Code.create :code => "757A", :explanation => "Onnettomuus, muu"
    Code.create :code => "757B", :explanation => "Onnettomuus, muu"
    Code.create :code => "757C", :explanation => "Onnettomuus, muu"
    Code.create :code => "761A", :explanation => "Verenvuoto suusta"
    Code.create :code => "761B", :explanation => "Verenvuoto suusta"
    Code.create :code => "761C", :explanation => "Verenvuoto suusta"
    Code.create :code => "762B", :explanation => "Verenvuoto gynekologinen/urologinen"
    Code.create :code => "762C", :explanation => "Verenvuoto gynekologinen/urologinen"
    Code.create :code => "762D", :explanation => "Verenvuoto gynekologinen/urologinen"
    Code.create :code => "763B", :explanation => "Verenvuoto korva/nenä"
    Code.create :code => "763C", :explanation => "Verenvuoto korva/nenä"
    Code.create :code => "763D", :explanation => "Verenvuoto korva/nenä"
    Code.create :code => "764B", :explanation => "Verenvuoto sääri/muu"
    Code.create :code => "764C", :explanation => "Verenvuoto sääri/muu"
    Code.create :code => "764D", :explanation => "Verenvuoto sääri/muu"
    Code.create :code => "770B", :explanation => "Sairauskohtaus"
    Code.create :code => "771A", :explanation => "Sokeritasapainon häiriö"
    Code.create :code => "771B", :explanation => "Sokeritasapainon häiriö"
    Code.create :code => "771C", :explanation => "Sokeritasapainon häiriö"
    Code.create :code => "772A", :explanation => "Kouristelu"
    Code.create :code => "772B", :explanation => "Kouristelu"
    Code.create :code => "772C", :explanation => "Kouristelu"
    Code.create :code => "772D", :explanation => "Kouristelu"
    Code.create :code => "773A", :explanation => "Yliherkkyysreaktio"
    Code.create :code => "773B", :explanation => "Yliherkkyysreaktio"
    Code.create :code => "773C", :explanation => "Yliherkkyysreaktio"
    Code.create :code => "773D", :explanation => "Yliherkkyysreaktio"
    Code.create :code => "774C", :explanation => "Heikentynyt yleistila"
    Code.create :code => "774D", :explanation => "Heikentynyt yleistila"
    Code.create :code => "775C", :explanation => "Oksentelu, ripuli"
    Code.create :code => "775D", :explanation => "Oksentelu, ripuli"
    Code.create :code => "781A", :explanation => "Vatsakipu"
    Code.create :code => "781B", :explanation => "Vatsakipu"
    Code.create :code => "781C", :explanation => "Vatsakipu"
    Code.create :code => "781D", :explanation => "Vatsakipu"
    Code.create :code => "782A", :explanation => "Pää/niskasärky"
    Code.create :code => "782B", :explanation => "Pää/niskasärky"
    Code.create :code => "782C", :explanation => "Pää/niskasärky"
    Code.create :code => "782D", :explanation => "Pää/niskasärky"
    Code.create :code => "783B", :explanation => "Selkä/raaja/vartalokipu"
    Code.create :code => "783C", :explanation => "Selkä/raaja/vartalokipu"
    Code.create :code => "783D", :explanation => "Selkä/raaja/vartalokipu"
    Code.create :code => "784C", :explanation => "Aistioire"
    Code.create :code => "784D", :explanation => "Aistioire"
    Code.create :code => "785C", :explanation => "Mielenterveysongelma"
    Code.create :code => "785D", :explanation => "Mielenterveysongelma"
    Code.create :code => "790B", :explanation => "Epäselvä tehtävä"
    Code.create :code => "791A", :explanation => "Synnytys"
    Code.create :code => "791B", :explanation => "Synnytys"
    Code.create :code => "791C", :explanation => "Synnytys"
    Code.create :code => "791D", :explanation => "Synnytys"
    Code.create :code => "792B", :explanation => "Uhkailu, varuillaolo"
    Code.create :code => "792C", :explanation => "Uhkailu, varuillaolo"
    Code.create :code => "793A", :explanation => "Hoitolaitossiirto"
    Code.create :code => "793B", :explanation => "Hoitolaitossiirto"
    Code.create :code => "793C", :explanation => "Hoitolaitossiirto"
    Code.create :code => "793D", :explanation => "Hoitolaitossiirto"
    Code.create :code => "794D", :explanation => "Muu sairaankuljetustehtävä"
    Code.create :code => "796A", :explanation => "Monipotilastilanne, suuronnettomuus"
    Code.create :code => "202A", :explanation => "Tieliikennonnettomuus, pieni"
    Code.create :code => "202B", :explanation => "Tieliikennonnettomuus, pieni"
    Code.create :code => "202C", :explanation => "Tieliikennonnettomuus, pieni"
    Code.create :code => "203A", :explanation => "Tieliikennonnettomuus, keskisuuri"
    Code.create :code => "203B", :explanation => "Tieliikennonnettomuus, keskisuuri"
    Code.create :code => "203C", :explanation => "Tieliikennonnettomuus, keskisuuri"
    Code.create :code => "204A", :explanation => "Tieliikennonnettomuus, suuri"
    Code.create :code => "204B", :explanation => "Tieliikennonnettomuus, suuri"
    Code.create :code => "212A", :explanation => "Raideliikennonnettomuus, pieni"
    Code.create :code => "212B", :explanation => "Raideliikennonnettomuus, pieni"
    Code.create :code => "213A", :explanation => "Raideliikennonnettomuus, keskisuuri"
    Code.create :code => "213B", :explanation => "Raideliikennonnettomuus, keskisuuri"
    Code.create :code => "214A", :explanation => "Raideliikennonnettomuus, suuri"
    Code.create :code => "214B", :explanation => "Raideliikennonnettomuus, suuri"
    Code.create :code => "220A", :explanation => "Vesiliikennonnettomuus, muu"
    Code.create :code => "220B", :explanation => "Vesiliikennonnettomuus, muu"
    Code.create :code => "221A", :explanation => "Vesiliikennonnettomuus, pieni"
    Code.create :code => "221B", :explanation => "Vesiliikennonnettomuus, pieni"
    Code.create :code => "222A", :explanation => "Vesiliikennonnettomuus, keskisuuri"
    Code.create :code => "222B", :explanation => "Vesiliikennonnettomuus, keskisuuri"
    Code.create :code => "223A", :explanation => "Vesiliikennonnettomuus, suuri"
    Code.create :code => "223B", :explanation => "Vesiliikennonnettomuus, suuri"
    
  end
    
  def self.down
    drop_table :codes
  end
end
    
